export const movieData = [
  {
    Title: "Guardians of the Galaxy Vol. 2",
    Year: "2017",
    Rated: "PG-13",
    Released: "05 May 2017",
    Runtime: "136 min",
    Genre: "Action, Adventure, Comedy",
    Director: "James Gunn",
    Writer: "James Gunn, Dan Abnett, Andy Lanning",
    Actors: "Chris Pratt, Zoe Saldana, Dave Bautista",
    Plot: "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father, the ambitious celestial being Ego.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 15 wins & 60 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.6/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "85%",
      },
      {
        Source: "Metacritic",
        Value: "67/100",
      },
    ],
    Metascore: "67",
    imdbRating: "7.6",
    imdbVotes: "757,026",
    imdbID: "tt3896198",
    Type: "movie",
    DVD: "10 Jul 2017",
    BoxOffice: "$389,813,101",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Forrest Gump",
    Year: "1994",
    Rated: "PG-13",
    Released: "06 Jul 1994",
    Runtime: "142 min",
    Genre: "Drama, Romance",
    Director: "Robert Zemeckis",
    Writer: "Winston Groom, Eric Roth",
    Actors: "Tom Hanks, Robin Wright, Gary Sinise",
    Plot: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
    Language: "English",
    Country: "United States",
    Awards: "Won 6 Oscars. 51 wins & 74 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.8/10" },
      { Source: "Rotten Tomatoes", Value: "76%" },
      { Source: "Metacritic", Value: "82/100" },
    ],
    Metascore: "82",
    imdbRating: "8.8",
    imdbVotes: "2,256,886",
    imdbID: "tt0109830",
    Type: "movie",
    DVD: "01 Aug 2013",
    BoxOffice: "$330,455,270",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Top Gun: Maverick",
    Year: "2022",
    Rated: "PG-13",
    Released: "27 May 2022",
    Runtime: "130 min",
    Genre: "Action, Drama",
    Director: "Joseph Kosinski",
    Writer: "Jim Cash, Jack Epps Jr., Peter Craig",
    Actors: "Tom Cruise, Jennifer Connelly, Miles Teller",
    Plot: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to ...",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Oscar. 107 wins & 234 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.2/10" },
      { Source: "Rotten Tomatoes", Value: "96%" },
      { Source: "Metacritic", Value: "78/100" },
    ],
    Metascore: "78",
    imdbRating: "8.2",
    imdbVotes: "695,684",
    imdbID: "tt1745960",
    Type: "movie",
    DVD: "22 Aug 2022",
    BoxOffice: "$718,732,821",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "WALL·E",
    Year: "2008",
    Rated: "G",
    Released: "27 Jun 2008",
    Runtime: "98 min",
    Genre: "Animation, Adventure, Family",
    Director: "Andrew Stanton",
    Writer: "Andrew Stanton, Pete Docter, Jim Reardon",
    Actors: "Ben Burtt, Elissa Knight, Jeff Garlin",
    Plot: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
    Language: "English, Russian, Ukrainian",
    Country: "United States, Japan",
    Awards: "Won 1 Oscar. 96 wins & 95 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.4/10" },
      { Source: "Rotten Tomatoes", Value: "95%" },
      { Source: "Metacritic", Value: "95/100" },
    ],
    Metascore: "95",
    imdbRating: "8.4",
    imdbVotes: "1,194,276",
    imdbID: "tt0910970",
    Type: "movie",
    DVD: "01 Jan 2014",
    BoxOffice: "$223,808,164",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Dark Knight",
    Year: "2008",
    Rated: "PG-13",
    Released: "18 Jul 2008",
    Runtime: "152 min",
    Genre: "Action, Crime, Drama",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Language: "English, Mandarin",
    Country: "United States, United Kingdom",
    Awards: "Won 2 Oscars. 163 wins & 164 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "9.0/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "84/100" },
    ],
    Metascore: "84",
    imdbRating: "9.0",
    imdbVotes: "2,869,224",
    imdbID: "tt0468569",
    Type: "movie",
    DVD: "14 Jun 2010",
    BoxOffice: "$534,987,076",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Wolf of Wall Street",
    Year: "2013",
    Rated: "R",
    Released: "25 Dec 2013",
    Runtime: "180 min",
    Genre: "Biography, Comedy, Crime",
    Director: "Martin Scorsese",
    Writer: "Terence Winter, Jordan Belfort",
    Actors: "Leonardo DiCaprio, Jonah Hill, Margot Robbie",
    Plot: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
    Language: "English, French",
    Country: "United States",
    Awards: "Nominated for 5 Oscars. 37 wins & 179 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.2/10" },
      { Source: "Rotten Tomatoes", Value: "80%" },
      { Source: "Metacritic", Value: "75/100" },
    ],
    Metascore: "75",
    imdbRating: "8.2",
    imdbVotes: "1,582,063",
    imdbID: "tt0993846",
    Type: "movie",
    DVD: "12 Dec 2015",
    BoxOffice: "$116,900,694",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
